//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSAKeyManager.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSAKeyManager.Languages.language_en", typeof(language_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypted Text.
        /// </summary>
        internal static string DecryptedText {
            get {
                return ResourceManager.GetString("DecryptedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted Text.
        /// </summary>
        internal static string EncryptedText {
            get {
                return ResourceManager.GetString("EncryptedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Key.
        /// </summary>
        internal static string ExportKey {
            get {
                return ResourceManager.GetString("ExportKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSA Key Manager.
        /// </summary>
        internal static string formMain {
            get {
                return ResourceManager.GetString("formMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Key Size.
        /// </summary>
        internal static string formSelectKeySize {
            get {
                return ResourceManager.GetString("formSelectKeySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a key type to export.
        /// </summary>
        internal static string formSelectKeyType {
            get {
                return ResourceManager.GetString("formSelectKeyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string formTest {
            get {
                return ResourceManager.GetString("formTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        internal static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Key.
        /// </summary>
        internal static string GenerateKey {
            get {
                return ResourceManager.GetString("GenerateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Key.
        /// </summary>
        internal static string ImportKey {
            get {
                return ResourceManager.GetString("ImportKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Information.
        /// </summary>
        internal static string KeyInformation {
            get {
                return ResourceManager.GetString("KeyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Size.
        /// </summary>
        internal static string KeySize {
            get {
                return ResourceManager.GetString("KeySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public keys could not use for decryption! Please use private key..
        /// </summary>
        internal static string msgDecryptCryptographicError {
            get {
                return ResourceManager.GetString("msgDecryptCryptographicError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decryption failed! Please be sure you are entering an encrypted text..
        /// </summary>
        internal static string msgDecryptError {
            get {
                return ResourceManager.GetString("msgDecryptError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during decryption..
        /// </summary>
        internal static string msgDecryptError2 {
            get {
                return ResourceManager.GetString("msgDecryptError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred trying to encrypt.
        /// </summary>
        internal static string msgEncryptError {
            get {
                return ResourceManager.GetString("msgEncryptError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Generated Successfully!.
        /// </summary>
        internal static string msgGenerated {
            get {
                return ResourceManager.GetString("msgGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation failed!.
        /// </summary>
        internal static string msgGenerateFailed {
            get {
                return ResourceManager.GetString("msgGenerateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Key Exported Successfully!.
        /// </summary>
        internal static string msgPrivateKeyExported {
            get {
                return ResourceManager.GetString("msgPrivateKeyExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Key Exported Successfully!.
        /// </summary>
        internal static string msgPublicKeyExported {
            get {
                return ResourceManager.GetString("msgPublicKeyExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a key size..
        /// </summary>
        internal static string msgSelectKeySize {
            get {
                return ResourceManager.GetString("msgSelectKeySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a key to export..
        /// </summary>
        internal static string msgSelectType {
            get {
                return ResourceManager.GetString("msgSelectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THERE IS NO KEY.
        /// </summary>
        internal static string NoKey {
            get {
                return ResourceManager.GetString("NoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Key.
        /// </summary>
        internal static string PrivateKey {
            get {
                return ResourceManager.GetString("PrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        internal static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Key.
        /// </summary>
        internal static string PublicKey {
            get {
                return ResourceManager.GetString("PublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended.
        /// </summary>
        internal static string Recommended {
            get {
                return ResourceManager.GetString("Recommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text To Decrypt.
        /// </summary>
        internal static string TextToDecrypt {
            get {
                return ResourceManager.GetString("TextToDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text To Encrypt.
        /// </summary>
        internal static string TextToEncrypt {
            get {
                return ResourceManager.GetString("TextToEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
